export type Category = "Espresso" | "Cold Drinks" | "Pastries" | "Sandwiches";
export type Badge =
  | "Popular"
  | "House Favorite"
  | "Staff Pick"
  | "New"
  | "Seasonal"
  | "Vegan"
  | "";

export interface MenuItem {
  id: string;
  category: Category;
  name: string;
  description: string;
  price: number;
  badge: Badge;
  imageUrl: string;
}

export const MENU_ITEMS: MenuItem[] = [
  // ── Espresso ───────────────────────────────────────────────────────────
  {
    id: "espresso",
    category: "Espresso",
    name: "Espresso",
    description: "A single concentrated shot of rich dark-roasted espresso with a golden crema",
    price: 3.75,
    badge: "",
    imageUrl: "/images/menu-espresso-01.jpg",
  },
  {
    id: "double-espresso",
    category: "Espresso",
    name: "Double Espresso",
    description: "Two back-to-back shots for a bolder and more intense espresso experience",
    price: 4.50,
    badge: "House Favorite",
    imageUrl: "/images/menu-espresso-02.jpg",
  },
  {
    id: "americano",
    category: "Espresso",
    name: "Americano",
    description: "Espresso shots pulled long with hot water for a smooth and clean cup",
    price: 4.25,
    badge: "",
    imageUrl: "/images/menu-espresso-03.jpg",
  },
  {
    id: "cappuccino",
    category: "Espresso",
    name: "Cappuccino",
    description: "Equal parts espresso and silky steamed milk finished with a thick dome of foam",
    price: 5.25,
    badge: "Popular",
    imageUrl: "/images/menu-espresso-04.jpg",
  },
  {
    id: "flat-white",
    category: "Espresso",
    name: "Flat White",
    description: "Ristretto shots with a thin layer of velvety microfoam — less milk more espresso",
    price: 5.50,
    badge: "House Favorite",
    imageUrl: "/images/menu-espresso-05.jpg",
  },
  {
    id: "latte",
    category: "Espresso",
    name: "Latte",
    description: "Double espresso with generous steamed milk and a whisper of foam on top",
    price: 5.75,
    badge: "Popular",
    imageUrl: "/images/menu-espresso-06.jpg",
  },
  {
    id: "cortado",
    category: "Espresso",
    name: "Cortado",
    description: "Equal pull of espresso and warm milk to cut the acidity without losing the body",
    price: 5.00,
    badge: "",
    imageUrl: "/images/menu-espresso-07.jpg",
  },
  {
    id: "macchiato",
    category: "Espresso",
    name: "Macchiato",
    description: "A double shot of espresso lightly stained with a dollop of foamed milk",
    price: 4.75,
    badge: "",
    imageUrl: "/images/menu-espresso-08.jpg",
  },
  {
    id: "mocha",
    category: "Espresso",
    name: "Mocha",
    description: "Espresso blended with rich dark chocolate sauce and topped with steamed milk",
    price: 6.25,
    badge: "Popular",
    imageUrl: "/images/menu-espresso-09.jpg",
  },
  {
    id: "espresso-con-panna",
    category: "Espresso",
    name: "Espresso con Panna",
    description: "A double shot of espresso crowned with a generous swirl of fresh whipped cream",
    price: 5.25,
    badge: "Staff Pick",
    imageUrl: "/images/menu-espresso-10.jpg",
  },
  {
    id: "caramel-latte",
    category: "Espresso",
    name: "Caramel Latte",
    description: "Smooth double-shot latte swirled with house-made salted caramel sauce",
    price: 6.50,
    badge: "Popular",
    imageUrl: "/images/menu-espresso-11.jpg",
  },
  {
    id: "hazelnut-cortado",
    category: "Espresso",
    name: "Hazelnut Cortado",
    description: "A cortado kissed with toasted hazelnut syrup and a dusting of cinnamon",
    price: 5.75,
    badge: "Seasonal",
    imageUrl: "/images/menu-espresso-12.jpg",
  },
  {
    id: "honey-oat-latte",
    category: "Espresso",
    name: "Honey Oat Latte",
    description: "Double espresso with oat milk and a swirl of raw wildflower honey",
    price: 6.25,
    badge: "New",
    imageUrl: "/images/menu-espresso-13.jpg",
  },
  {
    id: "vanilla-latte",
    category: "Espresso",
    name: "Vanilla Latte",
    description: "Classic double-shot latte sweetened with real Madagascar vanilla bean syrup",
    price: 6.00,
    badge: "",
    imageUrl: "/images/menu-espresso-14.jpg",
  },
  {
    id: "cardamom-cappuccino",
    category: "Espresso",
    name: "Cardamom Cappuccino",
    description: "Spiced cappuccino with freshly ground green cardamom and a hint of rose water",
    price: 5.75,
    badge: "House Favorite",
    imageUrl: "/images/menu-espresso-15.jpg",
  },

  // ── Cold Drinks ────────────────────────────────────────────────────────
  {
    id: "iced-latte",
    category: "Cold Drinks",
    name: "Iced Latte",
    description: "Double espresso chilled over ice and floated with cold whole milk",
    price: 5.75,
    badge: "Popular",
    imageUrl: "/images/menu-cold-01.jpg",
  },
  {
    id: "cold-brew",
    category: "Cold Drinks",
    name: "Cold Brew",
    description: "Coarsely ground beans steeped in cold water for 18 hours — smooth with low acidity",
    price: 5.50,
    badge: "House Favorite",
    imageUrl: "/images/menu-cold-02.jpg",
  },
  {
    id: "nitro-cold-brew",
    category: "Cold Drinks",
    name: "Nitro Cold Brew",
    description: "Cold brew infused with nitrogen for a creamy cascading texture straight from the tap",
    price: 6.25,
    badge: "Popular",
    imageUrl: "/images/menu-cold-03.jpg",
  },
  {
    id: "iced-americano",
    category: "Cold Drinks",
    name: "Iced Americano",
    description: "Shots pulled hot then poured over ice and topped with cold still water",
    price: 4.75,
    badge: "",
    imageUrl: "/images/menu-cold-04.jpg",
  },
  {
    id: "iced-mocha",
    category: "Cold Drinks",
    name: "Iced Mocha",
    description: "Cold espresso blended with chocolate sauce shaken with ice and topped with cold milk",
    price: 6.50,
    badge: "",
    imageUrl: "/images/menu-cold-05.jpg",
  },
  {
    id: "iced-matcha-latte",
    category: "Cold Drinks",
    name: "Iced Matcha Latte",
    description: "Ceremonial-grade matcha whisked smooth with oat milk over a bed of ice",
    price: 6.00,
    badge: "New",
    imageUrl: "/images/menu-cold-06.jpg",
  },
  {
    id: "caramel-frappuccino",
    category: "Cold Drinks",
    name: "Caramel Frappuccino",
    description: "Blended espresso with caramel sauce milk and ice finished with whipped cream",
    price: 7.50,
    badge: "Popular",
    imageUrl: "/images/menu-cold-07.jpg",
  },
  {
    id: "chocolate-mudslide-shake",
    category: "Cold Drinks",
    name: "Chocolate Mudslide Shake",
    description: "Thick chocolate shake blended with espresso dark cocoa and a ribbon of fudge",
    price: 7.75,
    badge: "House Favorite",
    imageUrl: "/images/menu-cold-08.jpg",
  },
  {
    id: "strawberry-lemonade",
    category: "Cold Drinks",
    name: "Strawberry Lemonade",
    description: "Fresh-squeezed lemonade muddled with ripe strawberries and a sprig of mint",
    price: 5.25,
    badge: "Seasonal",
    imageUrl: "/images/menu-cold-09.jpg",
  },
  {
    id: "hibiscus-iced-tea",
    category: "Cold Drinks",
    name: "Hibiscus Iced Tea",
    description: "Tart dried hibiscus brewed cold and sweetened lightly with agave nectar",
    price: 4.75,
    badge: "Vegan",
    imageUrl: "/images/menu-cold-10.jpg",
  },
  {
    id: "sparkling-cascara",
    category: "Cold Drinks",
    name: "Sparkling Cascara",
    description: "Cascara tea made from dried coffee cherry husks topped with sparkling water",
    price: 5.00,
    badge: "Staff Pick",
    imageUrl: "/images/menu-cold-11.jpg",
  },
  {
    id: "iced-chai-latte",
    category: "Cold Drinks",
    name: "Iced Chai Latte",
    description: "Bold spiced chai concentrate shaken with whole milk and poured over ice",
    price: 5.75,
    badge: "",
    imageUrl: "/images/menu-cold-12.jpg",
  },

  // ── Pastries ───────────────────────────────────────────────────────────
  {
    id: "butter-croissant",
    category: "Pastries",
    name: "Butter Croissant",
    description: "Layers of laminated dough baked to a deep amber with a shatteringly crisp exterior",
    price: 3.75,
    badge: "Popular",
    imageUrl: "/images/menu-pastry-01.jpg",
  },
  {
    id: "almond-croissant",
    category: "Pastries",
    name: "Almond Croissant",
    description: "Day-old croissant soaked in rum syrup filled with almond cream and toasted flakes",
    price: 4.75,
    badge: "House Favorite",
    imageUrl: "/images/menu-pastry-02.jpg",
  },
  {
    id: "pain-au-chocolat",
    category: "Pastries",
    name: "Pain au Chocolat",
    description: "Flaky croissant dough wrapped around two batons of 72% dark Belgian chocolate",
    price: 4.50,
    badge: "Popular",
    imageUrl: "/images/menu-pastry-03.jpg",
  },
  {
    id: "blueberry-muffin",
    category: "Pastries",
    name: "Blueberry Muffin",
    description: "Towering muffin bursting with wild blueberries and topped with crunchy sugar streusel",
    price: 4.25,
    badge: "",
    imageUrl: "/images/menu-pastry-04.jpg",
  },
  {
    id: "banana-bread",
    category: "Pastries",
    name: "Banana Bread",
    description: "Moist loaf made with overripe bananas brown butter and a ribbon of walnut",
    price: 4.00,
    badge: "House Favorite",
    imageUrl: "/images/menu-pastry-05.jpg",
  },
  {
    id: "morning-bun",
    category: "Pastries",
    name: "Morning Bun",
    description: "Spiral pastry rolled in cinnamon sugar with a hint of orange zest",
    price: 4.50,
    badge: "Staff Pick",
    imageUrl: "/images/menu-pastry-06.jpg",
  },
  {
    id: "cardamom-cinnamon-roll",
    category: "Pastries",
    name: "Cardamom Cinnamon Roll",
    description: "Giant pillowy roll swirled with cardamom butter and glazed with cream cheese icing",
    price: 5.75,
    badge: "Popular",
    imageUrl: "/images/menu-pastry-07.jpg",
  },
  {
    id: "matcha-kouign-amann",
    category: "Pastries",
    name: "Matcha Kouign-Amann",
    description: "Caramelized Breton pastry with a swirl of ceremonial matcha and sea salt",
    price: 5.25,
    badge: "New",
    imageUrl: "/images/menu-pastry-08.jpg",
  },
  {
    id: "lemon-poppy-seed-scone",
    category: "Pastries",
    name: "Lemon Poppy Seed Scone",
    description: "Crumbly scone with bright lemon zest and poppy seeds drizzled with a citrus glaze",
    price: 4.25,
    badge: "",
    imageUrl: "/images/menu-pastry-09.jpg",
  },
  {
    id: "pistachio-financier",
    category: "Pastries",
    name: "Pistachio Financier",
    description: "Buttery French almond cake enriched with roasted pistachio paste and honey",
    price: 4.50,
    badge: "Seasonal",
    imageUrl: "/images/menu-pastry-10.jpg",
  },
  {
    id: "double-chocolate-brownie",
    category: "Pastries",
    name: "Double Chocolate Brownie",
    description: "Dense fudge brownie with two types of chocolate and a flaky sea salt finish",
    price: 4.75,
    badge: "Popular",
    imageUrl: "/images/menu-pastry-11.jpg",
  },
  {
    id: "classic-shortbread",
    category: "Pastries",
    name: "Classic Shortbread",
    description: "Crisp Scottish-style biscuit made with just butter sugar and flour — and nothing else",
    price: 3.25,
    badge: "",
    imageUrl: "/images/menu-pastry-12.jpg",
  },

  // ── Sandwiches ─────────────────────────────────────────────────────────
  {
    id: "avocado-toast",
    category: "Sandwiches",
    name: "Avocado Toast",
    description: "Thick-cut sourdough with smashed avocado lemon zest red pepper flake and microgreens",
    price: 10.50,
    badge: "Popular",
    imageUrl: "/images/menu-sandwich-01.jpg",
  },
  {
    id: "egg-aged-cheddar-croissant",
    category: "Sandwiches",
    name: "Egg & Aged Cheddar Croissant",
    description: "Soft scrambled egg and sharp aged cheddar tucked inside a warm butter croissant",
    price: 9.75,
    badge: "House Favorite",
    imageUrl: "/images/menu-sandwich-02.jpg",
  },
  {
    id: "smoked-salmon-bagel",
    category: "Sandwiches",
    name: "Smoked Salmon Bagel",
    description: "Everything bagel with whipped cream cheese cucumber dill capers and smoked salmon",
    price: 13.50,
    badge: "Staff Pick",
    imageUrl: "/images/menu-sandwich-03.jpg",
  },
  {
    id: "turkey-and-brie",
    category: "Sandwiches",
    name: "Turkey & Brie",
    description: "Shaved turkey breast with creamy brie grain mustard and sliced apple on walnut bread",
    price: 12.75,
    badge: "",
    imageUrl: "/images/menu-sandwich-04.jpg",
  },
  {
    id: "caprese-panini",
    category: "Sandwiches",
    name: "Caprese Panini",
    description: "Fresh mozzarella heirloom tomato and basil pesto pressed on house-made focaccia",
    price: 11.00,
    badge: "Vegan",
    imageUrl: "/images/menu-sandwich-05.jpg",
  },
  {
    id: "blt-chipotle-mayo",
    category: "Sandwiches",
    name: "BLT with Chipotle Mayo",
    description: "Applewood-smoked bacon with butter lettuce tomato and smoky chipotle aioli on brioche",
    price: 11.50,
    badge: "Popular",
    imageUrl: "/images/menu-sandwich-06.jpg",
  },
  {
    id: "mushroom-gruyere-melt",
    category: "Sandwiches",
    name: "Mushroom & Gruyère Melt",
    description: "Sautéed wild mushrooms caramelized onions and melted gruyère on dark rye",
    price: 11.25,
    badge: "House Favorite",
    imageUrl: "/images/menu-sandwich-07.jpg",
  },
  {
    id: "chicken-pesto-club",
    category: "Sandwiches",
    name: "Chicken Pesto Club",
    description: "Sliced roasted chicken with sun-dried tomato pesto arugula and provolone on ciabatta",
    price: 13.00,
    badge: "",
    imageUrl: "/images/menu-sandwich-08.jpg",
  },
  {
    id: "ham-swiss-croissant",
    category: "Sandwiches",
    name: "Ham & Swiss Croissant",
    description: "Honey-glazed ham and Swiss cheese warmed in a freshly baked butter croissant",
    price: 10.25,
    badge: "",
    imageUrl: "/images/menu-sandwich-09.jpg",
  },
  {
    id: "veggie-hummus-wrap",
    category: "Sandwiches",
    name: "Veggie Hummus Wrap",
    description: "Roasted red pepper zucchini spinach and house hummus rolled in a whole-wheat tortilla",
    price: 9.50,
    badge: "Vegan",
    imageUrl: "/images/menu-sandwich-10.jpg",
  },
];
